# Sudoku Solver

## Backtracking Algorithm

<b>Note:</b>
- dfs used for traveral
- Can be identified as Greedy approach due to it's solving nature

#### Logic

- find empty cell
    if empty cell is not found, it means the puzzle is solved
- Make a guess (from 1 to 9)
- Validate by checking row col and box
    - if not, guess next number and again validate
- if the current guess doesn't work, bactrack

In [405]:
import numpy as np
import time
import timeit

In [406]:
class SudokuBacktrack():
    def __init__(self, grid):
        self.grid = grid
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.grid[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _validateGuess(self, row, col, guess):
        # Check for duplicate number in rows and columns
        for i in range(0, 9):
            if self.grid[row][i] == guess or guess == self.grid[i][col]:
                return False
            
        # Check for duplicate number in current box
        rowStart = (row // 3) * 3
        colStart = (col // 3) * 3
        for r in range(rowStart, rowStart + 3):
            for c in range(colStart, colStart + 3):
                if self.grid[r][c] == guess:
                    return False
            
        return True
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in range(1, 10):
            # Validation: check if number can be inserted 
            if self._validateGuess(row, col, guess):
                self.grid[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.grid[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        start_time = time.time()
        flag       = self._solve()
        total_time = time.time() - start_time
        
        if flag:
            print("Total time taken to solve:", round(total_time, 5), end="\n\n")
            print("Solved Sudoku Grid:")
            print(np.matrix(self.grid))
        else:
            print("Not a valid Sudoku puzzle")

In [407]:
grid = [[3, 9, 0,   0, 5, 0,   0, 0, 0],
        [0, 0, 0,   2, 0, 0,   0, 0, 5],
        [0, 0, 0,   7, 1, 9,   0, 8, 0],

        [0, 5, 0,   0, 6, 8,   0, 0, 0],
        [2, 0, 6,   0, 0, 3,   0, 0, 0],
        [0, 0, 0,   0, 0, 0,   0, 0, 4],

        [5, 0, 0,   0, 0, 0,   0, 0, 0],
        [6, 7, 0,   1, 0, 5,   0, 4, 0],
        [1, 0, 9,   0, 0, 0,   2, 0, 0]]

In [408]:
import copy

In [409]:
sudoku = SudokuBacktrack(copy.deepcopy(grid))

In [410]:
sudoku.solveSudoku()

Total time taken to solve: 0.02703

Solved Sudoku Grid:
[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]


In [411]:
grid2 = [[2, 0, 0,   0, 8, 0,   3, 0, 0],
        [0, 6, 0,   0, 7, 0,   0, 8, 4],
        [0, 3, 0,   5, 0, 0,   2, 0, 9],

        [0, 0, 0,   1, 0, 5,   4, 0, 8],
        [0, 0, 0,   0, 0, 0,   0, 0, 0],
        [4, 0, 2,   7, 0, 6,   0, 0, 0],

        [3, 0, 1,   0, 0, 7,   0, 4, 0],
        [7, 2, 0,   0, 4, 0,   0, 6, 0],
        [0, 0, 4,   0, 1, 0,   0, 0, 3]]

In [412]:
# grid2 = [[4, 0, 8,   5, 7, 1,   9, 0, 6],
#          [2, 7, 6,   8, 0, 9,   3, 0, 5],
#          [0, 1, 0,   0, 0, 0,   4, 0, 7],

#          [0, 0, 0,   4, 0, 8,   0, 6, 1],
#          [0, 2, 0,   0, 0, 0,   0, 0, 8],
#          [6, 0, 0,   7, 3, 0,   0, 9, 0],

#          [0, 0, 0,   0, 0, 3,   0, 7, 0],
#          [8, 0, 3,   0, 0, 0,   0, 0, 9],
#          [0, 9, 2,   1, 8, 0,   0, 0, 0]]

In [413]:
sudoku = SudokuBacktrack(copy.deepcopy(grid2))

In [414]:
sudoku.solveSudoku()

Total time taken to solve: 0.00489

Solved Sudoku Grid:
[[2 4 5 9 8 1 3 7 6]
 [1 6 9 2 7 3 5 8 4]
 [8 3 7 5 6 4 2 1 9]
 [9 7 6 1 2 5 4 3 8]
 [5 1 3 4 9 8 6 2 7]
 [4 8 2 7 3 6 9 5 1]
 [3 9 1 6 5 7 8 4 2]
 [7 2 8 3 4 9 1 6 5]
 [6 5 4 8 1 2 7 9 3]]


#### Measuring Time

In [282]:
class SudokuBacktrack():
    def __init__(self, grid):
        self.grid = grid
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.grid[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _validateGuess(self, row, col, guess):
        # Check for duplicate number in rows and columns
        for i in range(0, 9):
            if self.grid[row][i] == guess or guess == self.grid[i][col]:
                return False
            
        # Check for duplicate number in current box
        rowStart = (row // 3) * 3
        colStart = (col // 3) * 3
        for r in range(rowStart, rowStart + 3):
            for c in range(colStart, colStart + 3):
                if self.grid[r][c] == guess:
                    return False
            
        return True
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in range(1, 10):
            # Validation: check if number can be inserted 
            if self._validateGuess(row, col, guess):
                self.grid[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.grid[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        flag       = self._solve()
            
setup = '''
import numpy as np
import copy
from __main__ import SudokuBacktrack, grid
'''
code = '''
sudoku = SudokuBacktrack(copy.deepcopy(grid))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[286.30222089999734]


## Optimized Backtracking Algorithm

##### Optimizations

- Instead of guessing from 1-9, try only allowed values for a cell
    - Hashmaps
    - Initlization time: O(n*n)
- 

### Optimization 1: Stop unnecessary recurive calls for all possible guesses

In [283]:
class OptimizedSudokuBacktrack():
    def __init__(self, grid):
        self.grid = grid
        self.eligibleNumbers = {}
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.grid[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _validateGuess(self, row, col, guess):
        # Check for duplicate number in rows and columns
        for i in range(0, 9):
            if self.grid[row][i] == guess or guess == self.grid[i][col]:
                return False
            
        # Check for duplicate number in current box
        rowStart = (row // 3) * 3
        colStart = (col // 3) * 3
        for r in range(rowStart, rowStart + 3):
            for c in range(colStart, colStart + 3):
                if self.grid[r][c] == guess:
                    return False
        return True
    
    def _checkAllowedNumbers(self, row, col):
        possibleGuesses = [True] * 9
        for number in range(1, 10):
            # Checking in rows and columns
            for i in range(0, 9):
                if self.grid[row][i] == number or self.grid[i][col] == number:
                    possibleGuesses[number - 1] = False
                    break
                    
            if not possibleGuesses[number - 1]:
                continue
            
            # Checking in block
            rowStart = (row // 3) * 3
            colStart = (col // 3) * 3 
            for r in range(rowStart, rowStart + 3):
                for c in range(colStart, colStart + 3):
                    if self.grid[r][c] == number:
                        possibleGuesses[number - 1] = False
                        break
                if not possibleGuesses[number - 1]:
                    break
        
        return possibleGuesses
    
    def _findAllowedNumbersPerCell(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.grid[row][col] != 0:
                    continue
                    
                validNumbers     = self._checkAllowedNumbers(row, col)
                validNumbersList = []
                for i in range(len(validNumbers)):
                    if validNumbers[i]:
                        validNumbersList.append(i+1)
                self.eligibleNumbers[(row, col)] = validNumbersList
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in self.eligibleNumbers[(row, col)]:
            # Validation: check if number can be inserted 
            if self._validateGuess(row, col, guess):
                self.grid[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.grid[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        start_time = time.time()
        self._findAllowedNumbersPerCell()
        flag       = self._solve()
        total_time = time.time() - start_time
        
        if flag:
            print("Total time taken to solve:", round(total_time, 5), end="\n\n")
            print("Solved Sudoku Grid:")
            print(np.matrix(self.grid))
        else:
            print("Not a valid Sudoku puzzle")

In [284]:
grid

[[3, 9, 0, 0, 5, 0, 0, 0, 0],
 [0, 0, 0, 2, 0, 0, 0, 0, 5],
 [0, 0, 0, 7, 1, 9, 0, 8, 0],
 [0, 5, 0, 0, 6, 8, 0, 0, 0],
 [2, 0, 6, 0, 0, 3, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 4],
 [5, 0, 0, 0, 0, 0, 0, 0, 0],
 [6, 7, 0, 1, 0, 5, 0, 4, 0],
 [1, 0, 9, 0, 0, 0, 2, 0, 0]]

In [285]:
optimizedSudoku = OptimizedSudokuBacktrack(copy.deepcopy(grid))

In [286]:
optimizedSudoku.solveSudoku()

Total time taken to solve: 0.01826

Solved Sudoku Grid:
[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]


#### Measuring Time

In [287]:
class OptimizedSudokuBacktrack():
    def __init__(self, grid):
        self.grid = grid
        self.eligibleNumbers = {}
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.grid[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _validateGuess(self, row, col, guess):
        # Check for duplicate number in rows and columns
        for i in range(0, 9):
            if self.grid[row][i] == guess or guess == self.grid[i][col]:
                return False
            
        # Check for duplicate number in current box
        rowStart = (row // 3) * 3
        colStart = (col // 3) * 3
        for r in range(rowStart, rowStart + 3):
            for c in range(colStart, colStart + 3):
                if self.grid[r][c] == guess:
                    return False
        return True
    
    def _checkAllowedNumbers(self, row, col):
        possibleGuesses = [True] * 9
        for number in range(1, 10):
            # Checking in rows and columns
            for i in range(0, 9):
                if self.grid[row][i] == number or self.grid[i][col] == number:
                    possibleGuesses[number - 1] = False
                    break
                    
            if not possibleGuesses[number - 1]:
                continue
            
            # Checking in block
            rowStart = (row // 3) * 3
            colStart = (col // 3) * 3 
            for r in range(rowStart, rowStart + 3):
                for c in range(colStart, colStart + 3):
                    if self.grid[r][c] == number:
                        possibleGuesses[number - 1] = False
                        break
                if not possibleGuesses[number - 1]:
                    break
        
        return possibleGuesses
    
    def _findAllowedNumbersPerCell(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.grid[row][col] != 0:
                    continue
                    
                validNumbers     = self._checkAllowedNumbers(row, col)
                validNumbersList = []
                for i in range(len(validNumbers)):
                    if validNumbers[i]:
                        validNumbersList.append(i+1)
                self.eligibleNumbers[(row, col)] = validNumbersList
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in self.eligibleNumbers[(row, col)]:
            # Validation: check if number can be inserted 
            if self._validateGuess(row, col, guess):
                self.grid[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.grid[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        self._findAllowedNumbersPerCell()
        flag       = self._solve()
            
setup = '''
import numpy as np
import copy
from __main__ import OptimizedSudokuBacktrack, grid
'''
code = '''
sudoku = OptimizedSudokuBacktrack(copy.deepcopy(grid))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[217.98515640000187]


#### Optimization 2: Validate Guess Number

In [463]:
class OptimizedSudokuBacktrack():
    def __init__(self, grid):
        self.grid = grid
        self.eligibleNumbers = {}
        self.rowVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.colVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.blockVisitCache = [[False for i in range(9)] for j in range(9)]
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.grid[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _checkAllowedNumbers(self, row, col):
        possibleGuesses = [True] * 9
        for number in range(1, 10):
            # Checking in rows and columns
            for i in range(0, 9):
                if self.grid[row][i] == number or self.grid[i][col] == number:
                    possibleGuesses[number - 1] = False
                    break
                    
            if not possibleGuesses[number - 1]:
                continue
            
            # Checking in block
            rowStart = (row // 3) * 3
            colStart = (col // 3) * 3 
            for r in range(rowStart, rowStart + 3):
                for c in range(colStart, colStart + 3):
                    if self.grid[r][c] == number:
                        possibleGuesses[number - 1] = False
                        break
                if not possibleGuesses[number - 1]:
                    break
        
        return possibleGuesses
    
    def _findAllowedNumbersPerCell(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.grid[row][col] != 0:
                    continue
                    
                validNumbers     = self._checkAllowedNumbers(row, col)
                validNumbersList = []
                for i in range(len(validNumbers)):
                    if validNumbers[i]:
                        validNumbersList.append(i+1)
                self.eligibleNumbers[(row, col)] = validNumbersList
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in self.eligibleNumbers[(row, col)]:
            # Validation: check if number can be inserted 
            blockNumber = (row // 3) * 3 + col // 3
            # if self._validateGuess(row, col, guess):
            if not (self.rowVisitCache[row][guess - 1] or self.colVisitCache[col][guess - 1] \
                    or self.blockVisitCache[blockNumber][guess - 1]):
                self.rowVisitCache[row][guess - 1]           = True
                self.colVisitCache[col][guess - 1]           = True
                self.blockVisitCache[blockNumber][guess - 1] = True
                self.grid[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.rowVisitCache[row][guess - 1]           = False
                self.colVisitCache[col][guess - 1]           = False
                self.blockVisitCache[blockNumber][guess - 1] = False
                self.grid[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        start_time = time.time()
        self._findAllowedNumbersPerCell()
        flag       = self._solve()
        total_time = time.time() - start_time
        
        if flag:
            print("Total time taken to solve:", round(total_time, 5), end="\n\n")
            print("Solved Sudoku Grid:")
            print(np.matrix(self.grid))
        else:
            print("Not a valid Sudoku puzzle")

In [461]:
optimizedSudoku = OptimizedSudokuBacktrack(copy.deepcopy(grid))

In [462]:
optimizedSudoku.solveSudoku()

Total time taken to solve: 0.01402

Solved Sudoku Grid:
[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]


#### Measuring Time

In [464]:
class OptimizedSudokuBacktrack():
    def __init__(self, grid):
        self.grid = grid
        self.eligibleNumbers = {}
        self.rowVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.colVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.blockVisitCache = [[False for i in range(9)] for j in range(9)]
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.grid[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _checkAllowedNumbers(self, row, col):
        possibleGuesses = [True] * 9
        for number in range(1, 10):
            # Checking in rows and columns
            for i in range(0, 9):
                if self.grid[row][i] == number or self.grid[i][col] == number:
                    possibleGuesses[number - 1] = False
                    break
                    
            if not possibleGuesses[number - 1]:
                continue
            
            # Checking in block
            rowStart = (row // 3) * 3
            colStart = (col // 3) * 3 
            for r in range(rowStart, rowStart + 3):
                for c in range(colStart, colStart + 3):
                    if self.grid[r][c] == number:
                        possibleGuesses[number - 1] = False
                        break
                if not possibleGuesses[number - 1]:
                    break
        
        return possibleGuesses
    
    def _findAllowedNumbersPerCell(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.grid[row][col] != 0:
                    continue
                    
                validNumbers     = self._checkAllowedNumbers(row, col)
                validNumbersList = []
                for i in range(len(validNumbers)):
                    if validNumbers[i]:
                        validNumbersList.append(i+1)
                self.eligibleNumbers[(row, col)] = validNumbersList
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in self.eligibleNumbers[(row, col)]:
            # Validation: check if number can be inserted 
            blockNumber = (row // 3) * 3 + col // 3
            # if self._validateGuess(row, col, guess):
            if not (self.rowVisitCache[row][guess - 1] or self.colVisitCache[col][guess - 1] \
                    or self.blockVisitCache[blockNumber][guess - 1]):
                self.rowVisitCache[row][guess - 1]           = True
                self.colVisitCache[col][guess - 1]           = True
                self.blockVisitCache[blockNumber][guess - 1] = True
                self.grid[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.rowVisitCache[row][guess - 1]           = False
                self.colVisitCache[col][guess - 1]           = False
                self.blockVisitCache[blockNumber][guess - 1] = False
                self.grid[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        self._findAllowedNumbersPerCell()
        flag       = self._solve()
            
setup = '''
import numpy as np
import copy
from __main__ import OptimizedSudokuBacktrack, grid
'''
code = '''
sudoku = OptimizedSudokuBacktrack(copy.deepcopy(grid))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[135.54837209999823]


#### Optimization 3: Scanning but for single number occurence in either row, col, or block and repeat this process till it exists

In [569]:
class OptimizedSudokuBacktrack():
    def __init__(self, grid):
        self.grid = grid
        self.eligibleNumbers      = {}
        self.rowVisitCache        = [[False for i in range(9)] for j in range(9)]
        self.colVisitCache        = [[False for i in range(9)] for j in range(9)]
        self.blockVisitCache      = [[False for i in range(9)] for j in range(9)]
        self.rowNumberFrequency   = [[0 for i in range(9)] for j in range(9)]
        self.colNumberFrequency   = [[0 for i in range(9)] for j in range(9)]
        self.blockNumberFrequency = [[0 for i in range(9)] for j in range(9)]
        
    def _rowNumberCount(self, number):
        for row in range(9):
            count = 0
            for col in range(9):
                if self.grid[row][col] != 0:
                    continue

                if number in self.eligibleNumbers[(row, col)]:
                    count += 1
            self.rowNumberFrequency[row][number - 1] = count
    
    def _colNumberCount(self, number):
        for col in range(9):
            count = 0
            for row in range(9):
                key = (row, col)
                if self.grid[row][col] != 0:
                    continue

                if number in self.eligibleNumbers[key]:
                    count += 1
            self.colNumberFrequency[col][number - 1] = count
    
    def _blockNumberCount(self, number):
        rowStart = -3
        colStart = 0        
        for blockNumber in range(9):
            if blockNumber % 3 == 0:
                rowStart += 3
                colStart = 0

            count = 0
            for r in range(rowStart, rowStart + 3):
                for c in range(colStart, colStart + 3):
                    key = (r, c)
                    if self.grid[r][c] != 0:
                        continue

                    if number in self.eligibleNumbers[key]:
                        count += 1
            colStart += 3
            self.blockNumberFrequency[blockNumber][number - 1] = count
            
#     def _sortEligibleNumbersByIndex(self):
#         blockNumber = -1
#         for row in range(9):
#             for col in range(9):
#                 if row % 3 == 0 and col % 3 == 0:
#                     blockNumber += 1
#                 if self.grid[row][col] != 0:
#                     continue
                
#                 frequencyList = []
#                 for eligibleNumber in self.eligibleNumbers[(row, col)]:
#                     frequency = self.rowNumberFrequency[row][eligibleNumber - 1] + self.colNumberFrequency[col][eligibleNumber - 1] \
#                     + self.blockNumberFrequency[blockNumber][eligibleNumber - 1] - 2
#                     frequencyList.append(eligibleNumber)
                
                
#                 self.eligibleNumbers[(row, col)] = [number for _, number in sorted(zip(frequencyList, self.eligibleNumbers[(row, col)]))]
                    
    
    def _determineNumberAppearanceCount(self):
        for number in range(1, 10):
            self._rowNumberCount(number)
            self._colNumberCount(number)
            self._blockNumberCount(number)
            # self._sortEligibleNumbersByIndex()
    
    def _scanBoard(self):
        blockNumber = -1
        
        while (True):
            newValue = False
            for row in range(0, 9):
                for col in range(0, 9):
                    if self.grid[row][col] != 0:
                        continue
                    blockNumber = (row // 3) * 3 + col // 3
                    for number in self.eligibleNumbers[(row, col)]:
                        if self.rowNumberFrequency[row][number - 1] == 1 or self.colNumberFrequency[col][number -1] == 1 \
                        or self.blockNumberFrequency[blockNumber][number - 1] == 1:
                            self.grid[row][col] = number  
                            newValue = True
                            
            if not newValue:
                break
            self._findAllowedNumbersPerCell()
            self._determineNumberAppearanceCount()
                        
                    
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.grid[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _checkAllowedNumbers(self, row, col):
        possibleGuesses = [True] * 9
        for number in range(1, 10):
            # Checking in rows and columns
            for i in range(0, 9):
                if self.grid[row][i] == number or self.grid[i][col] == number:
                    possibleGuesses[number - 1] = False
                    break
                    
            if not possibleGuesses[number - 1]:
                continue
            
            # Checking in block
            rowStart = (row // 3) * 3
            colStart = (col // 3) * 3 
            for r in range(rowStart, rowStart + 3):
                for c in range(colStart, colStart + 3):
                    if self.grid[r][c] == number:
                        possibleGuesses[number - 1] = False
                        break
                if not possibleGuesses[number - 1]:
                    break
        
        return possibleGuesses
    
    def _findAllowedNumbersPerCell(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.grid[row][col] != 0:
                    continue
                    
                validNumbers     = self._checkAllowedNumbers(row, col)
                validNumbersList = []
                for i in range(len(validNumbers)):
                    if validNumbers[i]:
                        validNumbersList.append(i+1)
                self.eligibleNumbers[(row, col)] = validNumbersList
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in self.eligibleNumbers[(row, col)]:
            # Validation: check if number can be inserted 
            blockNumber = (row // 3) * 3 + col // 3
            # if self._validateGuess(row, col, guess):
            if not (self.rowVisitCache[row][guess - 1] or self.colVisitCache[col][guess - 1] \
                    or self.blockVisitCache[blockNumber][guess - 1]):
                self.rowVisitCache[row][guess - 1]           = True
                self.colVisitCache[col][guess - 1]           = True
                self.blockVisitCache[blockNumber][guess - 1] = True
                self.grid[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.rowVisitCache[row][guess - 1]           = False
                self.colVisitCache[col][guess - 1]           = False
                self.blockVisitCache[blockNumber][guess - 1] = False
                self.grid[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        start_time = time.time()
        self._findAllowedNumbersPerCell()
        self._determineNumberAppearanceCount()
        self._scanBoard()
        flag       = self._solve()
        total_time = time.time() - start_time
        
        if flag:
            print("Total time taken to solve:", round(total_time, 5), end="\n\n")
            print("Solved Sudoku Grid:")
            print(np.matrix(self.grid))
        else:
            print("Not a valid Sudoku puzzle")

In [570]:
optimizedSudoku = OptimizedSudokuBacktrack(copy.deepcopy(grid))

In [571]:
optimizedSudoku.solveSudoku()

Total time taken to solve: 0.0205

Solved Sudoku Grid:
[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]


#### Measuring Time

In [572]:
class OptimizedSudokuBacktrack():
    def __init__(self, grid):
        self.grid = grid
        self.eligibleNumbers      = {}
        self.rowVisitCache        = [[False for i in range(9)] for j in range(9)]
        self.colVisitCache        = [[False for i in range(9)] for j in range(9)]
        self.blockVisitCache      = [[False for i in range(9)] for j in range(9)]
        self.rowNumberFrequency   = [[0 for i in range(9)] for j in range(9)]
        self.colNumberFrequency   = [[0 for i in range(9)] for j in range(9)]
        self.blockNumberFrequency = [[0 for i in range(9)] for j in range(9)]
        
    def _rowNumberCount(self, number):
        for row in range(9):
            count = 0
            for col in range(9):
                if self.grid[row][col] != 0:
                    continue

                if number in self.eligibleNumbers[(row, col)]:
                    count += 1
            self.rowNumberFrequency[row][number - 1] = count
    
    def _colNumberCount(self, number):
        for col in range(9):
            count = 0
            for row in range(9):
                key = (row, col)
                if self.grid[row][col] != 0:
                    continue

                if number in self.eligibleNumbers[key]:
                    count += 1
            self.colNumberFrequency[col][number - 1] = count
    
    def _blockNumberCount(self, number):
        rowStart = -3
        colStart = 0        
        for blockNumber in range(9):
            if blockNumber % 3 == 0:
                rowStart += 3
                colStart = 0

            count = 0
            for r in range(rowStart, rowStart + 3):
                for c in range(colStart, colStart + 3):
                    key = (r, c)
                    if self.grid[r][c] != 0:
                        continue

                    if number in self.eligibleNumbers[key]:
                        count += 1
            colStart += 3
            self.blockNumberFrequency[blockNumber][number - 1] = count
            
#     def _sortEligibleNumbersByIndex(self):
#         blockNumber = -1
#         for row in range(9):
#             for col in range(9):
#                 if row % 3 == 0 and col % 3 == 0:
#                     blockNumber += 1
#                 if self.grid[row][col] != 0:
#                     continue
                
#                 frequencyList = []
#                 for eligibleNumber in self.eligibleNumbers[(row, col)]:
#                     frequency = self.rowNumberFrequency[row][eligibleNumber - 1] + self.colNumberFrequency[col][eligibleNumber - 1] \
#                     + self.blockNumberFrequency[blockNumber][eligibleNumber - 1] - 2
#                     frequencyList.append(eligibleNumber)
                
                
#                 self.eligibleNumbers[(row, col)] = [number for _, number in sorted(zip(frequencyList, self.eligibleNumbers[(row, col)]))]
                    
    
    def _determineNumberAppearanceCount(self):
        for number in range(1, 10):
            self._rowNumberCount(number)
            self._colNumberCount(number)
            self._blockNumberCount(number)
            # self._sortEligibleNumbersByIndex()
    
    def _scanBoard(self):
        blockNumber = -1
        
        while (True):
            newValue = False
            for row in range(0, 9):
                for col in range(0, 9):
                    if self.grid[row][col] != 0:
                        continue
                    blockNumber = (row // 3) * 3 + col // 3
                    for number in self.eligibleNumbers[(row, col)]:
                        if self.rowNumberFrequency[row][number - 1] == 1 or self.colNumberFrequency[col][number -1] == 1 \
                        or self.blockNumberFrequency[blockNumber][number - 1] == 1:
                            self.grid[row][col] = number  
                            newValue = True
                            
            if not newValue:
                break
            self._findAllowedNumbersPerCell()
            self._determineNumberAppearanceCount()
                        
                    
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.grid[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _checkAllowedNumbers(self, row, col):
        possibleGuesses = [True] * 9
        for number in range(1, 10):
            # Checking in rows and columns
            for i in range(0, 9):
                if self.grid[row][i] == number or self.grid[i][col] == number:
                    possibleGuesses[number - 1] = False
                    break
                    
            if not possibleGuesses[number - 1]:
                continue
            
            # Checking in block
            rowStart = (row // 3) * 3
            colStart = (col // 3) * 3 
            for r in range(rowStart, rowStart + 3):
                for c in range(colStart, colStart + 3):
                    if self.grid[r][c] == number:
                        possibleGuesses[number - 1] = False
                        break
                if not possibleGuesses[number - 1]:
                    break
        
        return possibleGuesses
    
    def _findAllowedNumbersPerCell(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.grid[row][col] != 0:
                    continue
                    
                validNumbers     = self._checkAllowedNumbers(row, col)
                validNumbersList = []
                for i in range(len(validNumbers)):
                    if validNumbers[i]:
                        validNumbersList.append(i+1)
                self.eligibleNumbers[(row, col)] = validNumbersList
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in self.eligibleNumbers[(row, col)]:
            # Validation: check if number can be inserted 
            blockNumber = (row // 3) * 3 + col // 3
            # if self._validateGuess(row, col, guess):
            if not (self.rowVisitCache[row][guess - 1] or self.colVisitCache[col][guess - 1] \
                    or self.blockVisitCache[blockNumber][guess - 1]):
                self.rowVisitCache[row][guess - 1]           = True
                self.colVisitCache[col][guess - 1]           = True
                self.blockVisitCache[blockNumber][guess - 1] = True
                self.grid[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.rowVisitCache[row][guess - 1]           = False
                self.colVisitCache[col][guess - 1]           = False
                self.blockVisitCache[blockNumber][guess - 1] = False
                self.grid[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        self._findAllowedNumbersPerCell()
        self._determineNumberAppearanceCount()
        self._scanBoard()
                    
setup = '''
import numpy as np
import copy
from __main__ import OptimizedSudokuBacktrack, grid
'''
code = '''
sudoku = OptimizedSudokuBacktrack(copy.deepcopy(grid))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[203.6468548999983]
