In [1]:
import numpy as np
import time
import timeit

In [2]:
class SudokuBacktrack():
    def __init__(self, board):
        self.board = board
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.board[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _validateGuess(self, row, col, guess):
        # Check for duplicate number in rows and columns
        for i in range(0, 9):
            if self.board[row][i] == guess or guess == self.board[i][col]:
                return False
            
        # Check for duplicate number in current box
        rowStart = (row // 3) * 3
        colStart = (col // 3) * 3
        for r in range(rowStart, rowStart + 3):
            for c in range(colStart, colStart + 3):
                if self.board[r][c] == guess:
                    return False
            
        return True
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in range(1, 10):
            # Validation: check if number can be inserted 
            if self._validateGuess(row, col, guess):
                self.board[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.board[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        flag       = self._solve()
        
        if flag:
            print("Solved Sudoku Grid:")
            print(np.matrix(self.board))
        else:
            print("Not a valid Sudoku puzzle")

In [3]:
board = [[3, 9, 0,   0, 5, 0,   0, 0, 0],
         [0, 0, 0,   2, 0, 0,   0, 0, 5],
         [0, 0, 0,   7, 1, 9,   0, 8, 0],

         [0, 5, 0,   0, 6, 8,   0, 0, 0],
         [2, 0, 6,   0, 0, 3,   0, 0, 0],
         [0, 0, 0,   0, 0, 0,   0, 0, 4],

         [5, 0, 0,   0, 0, 0,   0, 0, 0],
         [6, 7, 0,   1, 0, 5,   0, 4, 0],
         [1, 0, 9,   0, 0, 0,   2, 0, 0]]

board2 = [[2, 0, 0,   0, 8, 0,   3, 0, 0],
          [0, 6, 0,   0, 7, 0,   0, 8, 4],
          [0, 3, 0,   5, 0, 0,   2, 0, 9],

          [0, 0, 0,   1, 0, 5,   4, 0, 8],
          [0, 0, 0,   0, 0, 0,   0, 0, 0],
          [4, 0, 2,   7, 0, 6,   0, 0, 0],

          [3, 0, 1,   0, 0, 7,   0, 4, 0],
          [7, 2, 0,   0, 4, 0,   0, 6, 0],
          [0, 0, 4,   0, 1, 0,   0, 0, 3]]

board3 = [[4, 0, 8,   5, 7, 1,   9, 0, 6],
          [2, 7, 6,   8, 0, 9,   3, 0, 5],
          [0, 1, 0,   0, 0, 0,   4, 0, 7],

          [0, 0, 0,   4, 0, 8,   0, 6, 1],
          [0, 2, 0,   0, 0, 0,   0, 0, 8],
          [6, 0, 0,   7, 3, 0,   0, 9, 0],

          [0, 0, 0,   0, 0, 3,   0, 7, 0],
          [8, 0, 3,   0, 0, 0,   0, 0, 9],
          [0, 9, 2,   1, 8, 0,   0, 0, 0]]

In [4]:
import copy

In [5]:
start_time = time.monotonic()

sudoku = SudokuBacktrack(copy.deepcopy(board))
sudoku.solveSudoku()

total_time = time.monotonic() - start_time
print("Time taken:", round(total_time, 5))

Solved Sudoku Grid:
[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]
Time taken: 0.031


In [6]:
start_time = time.monotonic()

sudoku = SudokuBacktrack(copy.deepcopy(board2))
sudoku.solveSudoku()

total_time = time.monotonic() - start_time
print("Time taken:", round(total_time, 5))

Solved Sudoku Grid:
[[2 4 5 9 8 1 3 7 6]
 [1 6 9 2 7 3 5 8 4]
 [8 3 7 5 6 4 2 1 9]
 [9 7 6 1 2 5 4 3 8]
 [5 1 3 4 9 8 6 2 7]
 [4 8 2 7 3 6 9 5 1]
 [3 9 1 6 5 7 8 4 2]
 [7 2 8 3 4 9 1 6 5]
 [6 5 4 8 1 2 7 9 3]]
Time taken: 0.0


In [7]:
start_time = time.monotonic()

sudoku = SudokuBacktrack(copy.deepcopy(board3))
sudoku.solveSudoku()

total_time = time.monotonic() - start_time
print("Time taken:", round(total_time, 5))

Solved Sudoku Grid:
[[4 3 8 5 7 1 9 2 6]
 [2 7 6 8 4 9 3 1 5]
 [5 1 9 3 2 6 4 8 7]
 [3 5 7 4 9 8 2 6 1]
 [9 2 4 6 1 5 7 3 8]
 [6 8 1 7 3 2 5 9 4]
 [1 4 5 9 6 3 8 7 2]
 [8 6 3 2 5 7 1 4 9]
 [7 9 2 1 8 4 6 5 3]]
Time taken: 0.0


### Measuring Time

In [20]:
class SudokuBacktrack():
    def __init__(self, board):
        self.board = board
    
    def _findEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.board[row][col] == 0: # Empty cell found
                    return row, col
        
        return None, None
    
    def _validateGuess(self, row, col, guess):
        # Check for duplicate number in rows and columns
        for i in range(0, 9):
            if self.board[row][i] == guess or guess == self.board[i][col]:
                return False
            
        # Check for duplicate number in current box
        rowStart = (row // 3) * 3
        colStart = (col // 3) * 3
        for r in range(rowStart, rowStart + 3):
            for c in range(colStart, colStart + 3):
                if self.board[r][c] == guess:
                    return False
            
        return True
    
    def _solve(self):
        # Find empty cell
        row, col = self._findEmptyCell()
        
        # If empty cell is not found, it means that the puzzle is solved
        if row == None:
            return True
        
        # Guess number from 1 to 9
        for guess in range(1, 10):
            # Validation: check if number can be inserted 
            if self._validateGuess(row, col, guess):
                self.board[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.board[row][col] = 0 # Remove to try another guess for possible solution
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        self._solve()
        
setup = '''
import numpy as np
import copy
from __main__ import SudokuBacktrack, board
'''
code = '''
sudoku = SudokuBacktrack(copy.deepcopy(board))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[229.81331169999976]


In [35]:
setup = '''
import numpy as np
import copy
from __main__ import SudokuBacktrack, board2
'''
code = '''
sudoku = SudokuBacktrack(copy.deepcopy(board2))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[45.43086129999983]


In [36]:
setup = '''
import numpy as np
import copy
from __main__ import SudokuBacktrack, board3
'''
code = '''
sudoku = SudokuBacktrack(copy.deepcopy(board3))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[9.73802650000016]


### Optimization 1: Improve cell empty search and validate numbers faster 

In [22]:
class OptimizedSudokuBacktrack():
    def __init__(self, board):
        self.board           = board
        self.emptyCellsIndex = 0
        self.emptyCells      =  []
        self.rowVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.colVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.blockVisitCache = [[False for i in range(9)] for j in range(9)]
    
    def _findAllEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.board[row][col] == 0: # Empty cell found
                    self.emptyCells.append((row, col))
        
        return None, None
    
    def _scanBoard(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.board[row][col] == 0:
                    continue
                number = self.board[row][col]
                blockNumber = (row // 3) * 3 + col // 3
                self.rowVisitCache[row][number - 1]           = True
                self.colVisitCache[col][number - 1]           = True
                self.blockVisitCache[blockNumber][number - 1] = True
    
    def _solve(self):
        if self.emptyCellsIndex == len(self.emptyCells):
            return True
        
        row, col = self.emptyCells[self.emptyCellsIndex]
        
        # Guess number from 1 to 9
        for guess in range(1, 10):
            blockNumber = (row // 3) * 3 + col // 3
            
            # Validation: check if number can be inserted 
            if not (self.rowVisitCache[row][guess - 1] or self.colVisitCache[col][guess - 1] \
                    or self.blockVisitCache[blockNumber][guess - 1]):
                # Mark number visited on that row, col, or block
                self.rowVisitCache[row][guess - 1]           = True
                self.colVisitCache[col][guess - 1]           = True
                self.blockVisitCache[blockNumber][guess - 1] = True
                
                self.emptyCellsIndex += 1
                self.board[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.board[row][col] = 0 # Remove to try another guess for possible solution
                # Unmark number visited on that row, col, or block
                self.rowVisitCache[row][guess - 1]           = False
                self.colVisitCache[col][guess - 1]           = False
                self.blockVisitCache[blockNumber][guess - 1] = False
                self.emptyCellsIndex -= 1
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        self._scanBoard()
        self._findAllEmptyCell()
        flag =self._solve()
        
        if flag:
            print("Solved Sudoku Grid:")
            print(np.matrix(self.board))
        else:
            print("Not a valid Sudoku puzzle")

In [23]:
start_time = time.monotonic()

sudoku = OptimizedSudokuBacktrack(copy.deepcopy(board))
sudoku.solveSudoku()

total_time = time.monotonic() - start_time
print("Time taken:", round(total_time, 5))

Solved Sudoku Grid:
[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]
Time taken: 0.0


In [37]:
start_time = time.monotonic()

sudoku = OptimizedSudokuBacktrack(copy.deepcopy(board2))
sudoku.solveSudoku()

total_time = time.monotonic() - start_time
print("Time taken:", round(total_time, 5))

Solved Sudoku Grid:
[[2 4 5 9 8 1 3 7 6]
 [1 6 9 2 7 3 5 8 4]
 [8 3 7 5 6 4 2 1 9]
 [9 7 6 1 2 5 4 3 8]
 [5 1 3 4 9 8 6 2 7]
 [4 8 2 7 3 6 9 5 1]
 [3 9 1 6 5 7 8 4 2]
 [7 2 8 3 4 9 1 6 5]
 [6 5 4 8 1 2 7 9 3]]
Time taken: 0.016


In [38]:
start_time = time.monotonic()

sudoku = OptimizedSudokuBacktrack(copy.deepcopy(board))
sudoku.solveSudoku()

total_time = time.monotonic() - start_time
print("Time taken:", round(total_time, 5))

Solved Sudoku Grid:
[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]
Time taken: 0.0


### Measuring Time

In [20]:
class OptimizedSudokuBacktrack():
    def __init__(self, board):
        self.board           = board
        self.emptyCellsIndex = 0
        self.emptyCells      =  []
        self.rowVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.colVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.blockVisitCache = [[False for i in range(9)] for j in range(9)]
    
    def _findAllEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.board[row][col] == 0: # Empty cell found
                    self.emptyCells.append((row, col))
        
        return None, None
    
    def _scanBoard(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.board[row][col] == 0:
                    continue
                number = self.board[row][col]
                blockNumber = (row // 3) * 3 + col // 3
                self.rowVisitCache[row][number - 1]           = True
                self.colVisitCache[col][number - 1]           = True
                self.blockVisitCache[blockNumber][number - 1] = True
    
    def _solve(self):
        if self.emptyCellsIndex == len(self.emptyCells):
            return True
        
        row, col = self.emptyCells[self.emptyCellsIndex]
        
        # Guess number from 1 to 9
        for guess in range(1, 10):
            blockNumber = (row // 3) * 3 + col // 3
            
            # Validation: check if number can be inserted 
            if not (self.rowVisitCache[row][guess - 1] or self.colVisitCache[col][guess - 1] \
                    or self.blockVisitCache[blockNumber][guess - 1]):
                # Mark number visited on that row, col, or block
                self.rowVisitCache[row][guess - 1]           = True
                self.colVisitCache[col][guess - 1]           = True
                self.blockVisitCache[blockNumber][guess - 1] = True
                
                self.emptyCellsIndex += 1
                self.board[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.board[row][col] = 0 # Remove to try another guess for possible solution
                # Unmark number visited on that row, col, or block
                self.rowVisitCache[row][guess - 1]           = False
                self.colVisitCache[col][guess - 1]           = False
                self.blockVisitCache[blockNumber][guess - 1] = False
                self.emptyCellsIndex -= 1
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        self._scanBoard()
        self._findAllEmptyCell()
        self._solve()

In [21]:
setup = '''
import numpy as np
import copy
from __main__ import OptimizedSudokuBacktrack, board
'''
code = '''
sudoku = OptimizedSudokuBacktrack(copy.deepcopy(board))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[56.16806759999997]


In [12]:
setup = '''
import numpy as np
import copy
from __main__ import OptimizedSudokuBacktrack, board2
'''
code = '''
sudoku = OptimizedSudokuBacktrack(copy.deepcopy(board2))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[9.487914899999964]


In [13]:
setup = '''
import numpy as np
import copy
from __main__ import OptimizedSudokuBacktrack, board3
'''
code = '''
sudoku = OptimizedSudokuBacktrack(copy.deepcopy(board3))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[1.9666988000000174]


### Optimization 2: Iterate over valid numbers only 

In [39]:
class OptimizedSudokuBacktrack2():
    def __init__(self, board):
        self.board           = board
        self.emptyCellsIndex = 0
        self.emptyCells      =  []
        self.rowVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.colVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.blockVisitCache = [[False for i in range(9)] for j in range(9)]
        self.allowedNumbers  = {}
    
    def _findAllEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.board[row][col] == 0: # Empty cell found
                    self.emptyCells.append((row, col))
        return None, None
    
    def _finalAllowedNumbers(self, row, col):
        allowedNumberList = []
        for number in range(1, 10):
            found = False
            
            # Check for number in rows and columns
            for i in range(0, 9):
                if self.board[row][i] == number or number == self.board[i][col]:
                    found = True
            
            if not found:
                # Check for number in current box
                rowStart = (row // 3) * 3
                colStart = (col // 3) * 3
                for r in range(rowStart, rowStart + 3):
                    for c in range(colStart, colStart + 3):
                        if self.board[r][c] == number:
                            found = True
                            break
                    if found:
                        break

            if not found:
                allowedNumberList.append(number)
        return allowedNumberList
            
    
    def _scanBoard(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.board[row][col] == 0:
                    self.allowedNumbers[(row, col)] = self._finalAllowedNumbers(row, col)
                    continue
                number = self.board[row][col]
                blockNumber = (row // 3) * 3 + col // 3
                self.rowVisitCache[row][number - 1]           = True
                self.colVisitCache[col][number - 1]           = True
                self.blockVisitCache[blockNumber][number - 1] = True
    
    def _solve(self):
        if self.emptyCellsIndex == len(self.emptyCells):
            return True
        
        row, col = self.emptyCells[self.emptyCellsIndex]
        
        # Guess number from 1 to 9
        for guess in self.allowedNumbers[(row, col)]:
            blockNumber = (row // 3) * 3 + col // 3
            
            # Validation: check if number can be inserted 
            if not (self.rowVisitCache[row][guess - 1] or self.colVisitCache[col][guess - 1] \
                    or self.blockVisitCache[blockNumber][guess - 1]):
                # Mark number visited on that row, col, or block
                self.rowVisitCache[row][guess - 1]           = True
                self.colVisitCache[col][guess - 1]           = True
                self.blockVisitCache[blockNumber][guess - 1] = True
                
                self.emptyCellsIndex += 1
                self.board[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.board[row][col] = 0 # Remove to try another guess for possible solution
                # Unmark number visited on that row, col, or block
                self.rowVisitCache[row][guess - 1]           = False
                self.colVisitCache[col][guess - 1]           = False
                self.blockVisitCache[blockNumber][guess - 1] = False
                self.emptyCellsIndex -= 1
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        self._scanBoard()
        self._findAllEmptyCell()
        flag = self._solve()
        
        if flag:
            print("Solved Sudoku Grid:")
            print(np.matrix(self.board))
        else:
            print("Not a valid Sudoku puzzle")

In [32]:
start_time = time.monotonic()

sudoku = OptimizedSudokuBacktrack2(copy.deepcopy(board))
sudoku.solveSudoku()

total_time = time.monotonic() - start_time
print("Time taken:", round(total_time, 5))

Solved Sudoku Grid:
[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]
Time taken: 0.0


In [34]:
start_time = time.monotonic()

sudoku = OptimizedSudokuBacktrack2(copy.deepcopy(board2))
sudoku.solveSudoku()

total_time = time.monotonic() - start_time
print("Time taken:", round(total_time, 5))

Solved Sudoku Grid:
[[2 4 5 9 8 1 3 7 6]
 [1 6 9 2 7 3 5 8 4]
 [8 3 7 5 6 4 2 1 9]
 [9 7 6 1 2 5 4 3 8]
 [5 1 3 4 9 8 6 2 7]
 [4 8 2 7 3 6 9 5 1]
 [3 9 1 6 5 7 8 4 2]
 [7 2 8 3 4 9 1 6 5]
 [6 5 4 8 1 2 7 9 3]]
Time taken: 0.0


In [36]:
start_time = time.monotonic()

sudoku = OptimizedSudokuBacktrack2(copy.deepcopy(board3))
sudoku.solveSudoku()

total_time = time.monotonic() - start_time
print("Time taken:", round(total_time, 5))

Solved Sudoku Grid:
[[4 3 8 5 7 1 9 2 6]
 [2 7 6 8 4 9 3 1 5]
 [5 1 9 3 2 6 4 8 7]
 [3 5 7 4 9 8 2 6 1]
 [9 2 4 6 1 5 7 3 8]
 [6 8 1 7 3 2 5 9 4]
 [1 4 5 9 6 3 8 7 2]
 [8 6 3 2 5 7 1 4 9]
 [7 9 2 1 8 4 6 5 3]]
Time taken: 0.016


### Measuring Time

In [40]:
class OptimizedSudokuBacktrack2():
    def __init__(self, board):
        self.board           = board
        self.emptyCellsIndex = 0
        self.emptyCells      =  []
        self.rowVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.colVisitCache   = [[False for i in range(9)] for j in range(9)]
        self.blockVisitCache = [[False for i in range(9)] for j in range(9)]
        self.allowedNumbers  = {}
    
    def _findAllEmptyCell(self):
        for row in range(9):
            for col in range(9):
                if self.board[row][col] == 0: # Empty cell found
                    self.emptyCells.append((row, col))
        return None, None
    
    def _finalAllowedNumbers(self, row, col):
        allowedNumberList = []
        for number in range(1, 10):
            found = False
            
            # Check for number in rows and columns
            for i in range(0, 9):
                if self.board[row][i] == number or number == self.board[i][col]:
                    found = True
            
            if not found:
                # Check for number in current box
                rowStart = (row // 3) * 3
                colStart = (col // 3) * 3
                for r in range(rowStart, rowStart + 3):
                    for c in range(colStart, colStart + 3):
                        if self.board[r][c] == number:
                            found = True
                            break
                    if found:
                        break

            if not found:
                allowedNumberList.append(number)
        return allowedNumberList
            
    
    def _scanBoard(self):
        for row in range(0, 9):
            for col in range(0, 9):
                if self.board[row][col] == 0:
                    self.allowedNumbers[(row, col)] = self._finalAllowedNumbers(row, col)
                    continue
                number = self.board[row][col]
                blockNumber = (row // 3) * 3 + col // 3
                self.rowVisitCache[row][number - 1]           = True
                self.colVisitCache[col][number - 1]           = True
                self.blockVisitCache[blockNumber][number - 1] = True
    
    def _solve(self):
        if self.emptyCellsIndex == len(self.emptyCells):
            return True
        
        row, col = self.emptyCells[self.emptyCellsIndex]
        
        # Guess number from 1 to 9
        for guess in self.allowedNumbers[(row, col)]:
            blockNumber = (row // 3) * 3 + col // 3
            
            # Validation: check if number can be inserted 
            if not (self.rowVisitCache[row][guess - 1] or self.colVisitCache[col][guess - 1] \
                    or self.blockVisitCache[blockNumber][guess - 1]):
                # Mark number visited on that row, col, or block
                self.rowVisitCache[row][guess - 1]           = True
                self.colVisitCache[col][guess - 1]           = True
                self.blockVisitCache[blockNumber][guess - 1] = True
                
                self.emptyCellsIndex += 1
                self.board[row][col] = guess # if yes, put number in the cell
                flag = self._solve() # Solve for another empty cell
                if flag: # if solution is already found
                    return flag
                
                self.board[row][col] = 0 # Remove to try another guess for possible solution
                # Unmark number visited on that row, col, or block
                self.rowVisitCache[row][guess - 1]           = False
                self.colVisitCache[col][guess - 1]           = False
                self.blockVisitCache[blockNumber][guess - 1] = False
                self.emptyCellsIndex -= 1
        
        # If the current combination is not working, backtrack and try another number 
        return False
    
    def solveSudoku(self,):
        self._scanBoard()
        self._findAllEmptyCell()
        self._solve()


In [42]:
setup = '''
import numpy as np
import copy
from __main__ import OptimizedSudokuBacktrack2, board
'''
code = '''
sudoku = OptimizedSudokuBacktrack2(copy.deepcopy(board))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[57.75594359999923]


In [43]:
setup = '''
import numpy as np
import copy
from __main__ import OptimizedSudokuBacktrack2, board2
'''
code = '''
sudoku = OptimizedSudokuBacktrack2(copy.deepcopy(board2))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[19.96063359999971]


In [44]:
setup = '''
import numpy as np
import copy
from __main__ import OptimizedSudokuBacktrack2, board3
'''
code = '''
sudoku = OptimizedSudokuBacktrack2(copy.deepcopy(board3))
sudoku.solveSudoku()
'''

executionTime = timeit.repeat(setup = setup,
                              stmt = code,
                              repeat = 1,
                              number = 10000)
print(executionTime)

[11.59771560000081]
